from playwright.sync_api import expect, Page


class TestEmployee:
    def test_add_valid_employee(self, page: Page):
        page.locator("xpath=//input[@name='username']").fill("Admin")
        page.locator("xpath=//input[@name='password']").fill("admin123")
        page.locator("xpath=//button[normalize-space()='Login']").click()
        # click on PIM Menu
        # click on Add Employee
        # enter firstname as john
        # enter middlename as m
        # enter lastname as wick
        # click on save
        # verify the profile name - john wick
        # verify the textbox first name - john
        # expect(page.locator("xpath=//input[@name='firstName']")).to_have_value("john")

        # note employee id is autogenerated sometimes it fails because of concurrent user. just rerun if run fails. 
